version: '3.8'

services:
  auctionfrontend:
    build:  
      context: ./frontend
      args:
       # need to embed variables during build
       # can change this to change url when running frontend in docker-desktop container
       # change to aggregator url or ingress url
        - REACT_APP_dockerauthserver=http://localhost:8085/api/user/
        - REACT_APP_dockerauctionmanagerserver=http://localhost:8085/auctionroom/
        - REACT_APP_dockerauctiondetailsserver=http://localhost:8085/api/auctiondetails/
        - REACT_APP_dockercurrencymanagementserver=http://localhost:8085/api/currency/
        - REACT_APP_dockerauctionroomserver=http://localhost:8085/api/room/
    image: auctionfrontend
    ports:
      - "80:3000"
    
  #   # environment:
  #     # react env variables need to start with REACT_APP_
  #     # REACT_APP_dockerauthserver: host.docker.internal:8000
    
  auctionbackend-useraccount:
    build:  
      context: ./backend/useraccount
    image: auctionbackend-useraccount
    ports:
      - "8000:8080"
    environment:
      backend: mongodb://host.docker.internal:27017/useraccounts

  auctionbackend-currencymanagement:
    build:  
      context: ./backend/currencymanagement
    image: auctionbackend-currencymanagement
    ports:
      - "8001:8080"
    environment:
      backend: mongodb://host.docker.internal:27017/useraccounts
  
  auctionbackend-auctionroom:
    build:  
      context: ./backend/auctionroom
    image: auctionbackend-auctionroom
    ports:
      - "8002:8080"

  auctionbackend-auctionroommanager:
    build:  
      context: ./backend/auctionroommanager
      args:
       # need to embed variables during build
       # can change this to change url when running frontend in docker-desktop container
       # change to aggregator url or ingress url
        - redis_cluster_url=redis-leader.default.svc.cluster.local
    image: auctionbackend-auctionroommanager
    
    ports:
      - "9000:9000"

  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
      
  auctionbackend-auctiondetails:
    build:  
      context: ./backend/auctiondetails
    image: auctionbackend-auctiondetails
    ports:
      - "7000:8080"
    environment:
        backend: mongodb://host.docker.internal:27017/auctiondetails
        PORT: "8080"



